name: Test PIA VPN Connection (Docker)
on:
  push:           # Runs automatically on each commit
  workflow_dispatch:  # Also allows manual triggering
jobs:
  test-pia-manual:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Test Network Connectivity
        run: |
          echo "Testing basic network connectivity..."
          curl -v https://api.github.com/meta | head -20
          echo "Testing connection to port 53 (UDP/DNS)..."
          dig @8.8.8.8 google.com
          
      - name: Run PIA VPN Connection
        run: |
          # Disable immediate exit on error in the host shell so we can capture the exit code.
          set +e
          docker run --rm --privileged --security-opt seccomp=unconfined --security-opt apparmor=unconfined ubuntu:latest bash -c '
            set -e
            export DEBIAN_FRONTEND=noninteractive
            echo "Installing dependencies..."
            apt update && apt install -y --no-install-recommends curl wget openvpn ca-certificates iproute2 dnsutils
            
            echo "Testing network from inside Docker container..."
            echo "Current network interfaces:"
            ip a
            echo "Testing DNS:"
            dig github.com || echo "DNS lookup failed"
            
            echo "Setting up OpenVPN configuration..."
            mkdir -p /tmp/pia
            
            # Create minimal OpenVPN config using UDP port 53 (DNS port - likely to be allowed)
            echo "client" > /tmp/pia/pia.ovpn
            echo "dev tun" >> /tmp/pia/pia.ovpn
            echo "proto udp" >> /tmp/pia/pia.ovpn
            # Try using UDP port 53 (DNS port)
            echo "remote 193.37.253.181 53" >> /tmp/pia/pia.ovpn
            echo "resolv-retry infinite" >> /tmp/pia/pia.ovpn
            echo "nobind" >> /tmp/pia/pia.ovpn
            echo "persist-key" >> /tmp/pia/pia.ovpn
            echo "persist-tun" >> /tmp/pia/pia.ovpn
            # Use modern cipher configuration
            echo "data-ciphers AES-256-GCM:AES-128-GCM:CHACHA20-POLY1305" >> /tmp/pia/pia.ovpn
            echo "auth SHA256" >> /tmp/pia/pia.ovpn
            echo "tls-client" >> /tmp/pia/pia.ovpn
            echo "remote-cert-tls server" >> /tmp/pia/pia.ovpn
            echo "auth-user-pass /tmp/pia/auth.txt" >> /tmp/pia/pia.ovpn
            echo "comp-lzo" >> /tmp/pia/pia.ovpn
            echo "verb 4" >> /tmp/pia/pia.ovpn
            echo "reneg-sec 0" >> /tmp/pia/pia.ovpn
            # Add explicit DNS settings
            echo "dhcp-option DNS 8.8.8.8" >> /tmp/pia/pia.ovpn
            echo "dhcp-option DNS 8.8.4.4" >> /tmp/pia/pia.ovpn
            
            # Download CA certificate
            wget -q https://raw.githubusercontent.com/pia-foss/manual-connections/master/ca.rsa.4096.crt -O /tmp/pia/ca.rsa.4096.crt
            echo "ca /tmp/pia/ca.rsa.4096.crt" >> /tmp/pia/pia.ovpn
            
            echo "Creating credentials file..."
            echo "${{ secrets.PIA_USERNAME }}" > /tmp/pia/auth.txt
            echo "${{ secrets.PIA_PASSWORD }}" >> /tmp/pia/auth.txt
            chmod 600 /tmp/pia/auth.txt
            
            echo "Displaying final OpenVPN config (with credentials redacted):"
            cat /tmp/pia/pia.ovpn
            
            echo "Starting OpenVPN connection..."
            openvpn --config /tmp/pia/pia.ovpn --daemon --log /tmp/openvpn.log
            
            echo "Waiting for VPN interface to establish..."
            for i in $(seq 1 15); do
              echo "Checking for VPN interface (attempt $i)..."
              if ip a | grep -q tun0; then
                echo "VPN interface detected!"
                ip a show tun0
                echo "VPN connection successful!"
                exit 0
              fi
              # Show logs every few attempts
              if [ $((i % 3)) -eq 0 ]; then
                echo "Current OpenVPN log (attempt $i):"
                tail -n 15 /tmp/openvpn.log
              fi
              sleep 4
            done
            
            echo "VPN connection timed out. Full OpenVPN logs:"
            cat /tmp/openvpn.log
            exit 1
          '
          exit_code=$?
          echo "Docker run exit code: $exit_code"
          exit $exit_code
