name: Test PIA VPN Connection (Docker)
on:
  push:           # Runs automatically on each commit
  workflow_dispatch:  # Also allows manual triggering
jobs:
  test-pia-manual:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Run PIA VPN Connection
        run: |
          # Disable immediate exit on error in the host shell so we can capture the exit code.
          set +e
          docker run --rm --privileged --security-opt seccomp=unconfined --security-opt apparmor=unconfined ubuntu:latest bash -c '
            set -e
            export DEBIAN_FRONTEND=noninteractive
            echo "Installing dependencies..."
            apt update && apt install -y --no-install-recommends curl wget openvpn ca-certificates
            
            echo "Setting up OpenVPN configuration..."
            mkdir -p /tmp/pia
            
            # Create minimal OpenVPN config without using heredoc
            echo "client" > /tmp/pia/pia.ovpn
            echo "dev tun" >> /tmp/pia/pia.ovpn
            echo "proto tcp" >> /tmp/pia/pia.ovpn
            echo "remote ny.privateinternetaccess.com 443" >> /tmp/pia/pia.ovpn
            echo "resolv-retry infinite" >> /tmp/pia/pia.ovpn
            echo "nobind" >> /tmp/pia/pia.ovpn
            echo "persist-key" >> /tmp/pia/pia.ovpn
            echo "persist-tun" >> /tmp/pia/pia.ovpn
            echo "cipher aes-128-cbc" >> /tmp/pia/pia.ovpn
            echo "auth sha1" >> /tmp/pia/pia.ovpn
            echo "tls-client" >> /tmp/pia/pia.ovpn
            echo "remote-cert-tls server" >> /tmp/pia/pia.ovpn
            echo "auth-user-pass /tmp/pia/auth.txt" >> /tmp/pia/pia.ovpn
            echo "comp-lzo" >> /tmp/pia/pia.ovpn
            echo "verb 1" >> /tmp/pia/pia.ovpn
            echo "reneg-sec 0" >> /tmp/pia/pia.ovpn
            
            # Download CA certificate
            wget -q https://raw.githubusercontent.com/pia-foss/manual-connections/master/ca.rsa.4096.crt -O /tmp/pia/ca.rsa.4096.crt
            echo "ca /tmp/pia/ca.rsa.4096.crt" >> /tmp/pia/pia.ovpn
            
            echo "Creating credentials file..."
            echo "${{ secrets.PIA_USERNAME }}" > /tmp/pia/auth.txt
            echo "${{ secrets.PIA_PASSWORD }}" >> /tmp/pia/auth.txt
            chmod 600 /tmp/pia/auth.txt
            
            echo "Starting OpenVPN connection..."
            openvpn --config /tmp/pia/pia.ovpn --daemon --log /tmp/openvpn.log
            
            echo "Waiting for VPN interface to establish..."
            for i in $(seq 1 10); do
              echo "Checking for VPN interface (attempt $i)..."
              if ip a | grep -q tun0; then
                echo "VPN interface detected!"
                ip a show tun0
                echo "VPN connection successful!"
                exit 0
              fi
              sleep 3
            done
            
            echo "VPN connection timed out. OpenVPN logs:"
            cat /tmp/openvpn.log
            exit 1
          '
          exit_code=$?
          echo "Docker run exit code: $exit_code"
          exit $exit_code
