name: Test PIA VPN Connection (Docker)
on:
  push:           # Runs automatically on each commit
  workflow_dispatch:  # Also allows manual triggering
jobs:
  test-pia-manual:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Run PIA VPN using manual installation
        run: |
          # Disable immediate exit on error in the host shell so we can capture the exit code.
          set +e
          docker run --rm --privileged --security-opt seccomp=unconfined --security-opt apparmor=unconfined ubuntu:latest bash -c '
            set -e
            export DEBIAN_FRONTEND=noninteractive
            echo "Installing base dependencies..."
            apt update && apt install -y --no-install-recommends curl wget sudo iproute2 apt-transport-https gnupg ca-certificates openvpn unzip net-tools iputils-ping dnsutils
            
            # Check initial network state
            echo "Initial network configuration:"
            ip a
            echo "Initial DNS configuration:"
            cat /etc/resolv.conf
            echo "Initial public IP:"
            curl -v https://api64.ipify.org
            
            echo "Downloading PIA OpenVPN configurations..."
            mkdir -p /etc/openvpn/pia
            cd /etc/openvpn/pia
            wget -q https://www.privateinternetaccess.com/openvpn/openvpn.zip
            unzip -o openvpn.zip
            ls -la  # List the available configuration files
            
            echo "Creating credentials file..."
            echo "${{ secrets.PIA_USERNAME }}" > /etc/openvpn/pia/auth.txt
            echo "${{ secrets.PIA_PASSWORD }}" >> /etc/openvpn/pia/auth.txt
            chmod 600 /etc/openvpn/pia/auth.txt
            
            echo "Starting OpenVPN connection with logging..."
            # Modify the OpenVPN config to use TCP instead of UDP (sometimes helps in restricted environments)
            cp /etc/openvpn/pia/us_east.ovpn /etc/openvpn/pia/us_east_tcp.ovpn
            sed -i "s/udp/tcp/" /etc/openvpn/pia/us_east_tcp.ovpn
            
            # Start OpenVPN in the background with logging
            sudo openvpn --config /etc/openvpn/pia/us_east_tcp.ovpn --auth-user-pass /etc/openvpn/pia/auth.txt --daemon --log /var/log/openvpn.log --verb 4
            
            echo "Waiting for connection to establish..."
            for i in $(seq 1 30); do
              echo "Checking connection attempt $i..."
              if ip a | grep -q tun0; then
                echo "VPN interface detected!"
                break
              fi
              sleep 2
              
              # Check OpenVPN logs
              if [ $i -eq 10 ] || [ $i -eq 20 ]; then
                echo "Current OpenVPN log:"
                tail -n 50 /var/log/openvpn.log
              fi
            done
            
            # Check if VPN interface exists
            if ! ip a | grep -q tun0; then
              echo "VPN interface not found after waiting. Showing logs:"
              cat /var/log/openvpn.log
              echo "Network interfaces:"
              ip a
              exit 1
            fi
            
            echo "VPN interface found, checking routing:"
            ip route
            
            echo "Testing connection..."
            echo "Current public IP: $(curl -s https://api64.ipify.org)"
            
            # Check if we can get the IP
            current_ip=$(curl -s https://api64.ipify.org)
            if [[ -z "$current_ip" ]]; then
              echo "Failed to get current IP. Connection may have failed."
              echo "Full OpenVPN logs:"
              cat /var/log/openvpn.log
              exit 1
            fi
            
            echo "VPN connection successful with IP: $current_ip"
          '
          rc=$?
          echo "Docker run exit code: $rc"
          if [ $rc -eq 125 ]; then
            echo "Ignoring exit code 125 from Docker cleanup error."
            exit 0
          else
            exit $rc
          fi
