name: Rumble Visit with VPN in Container

on:
  push:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:
    inputs:
      video_url:
        description: "Rumble Video URL"
        required: true
        default: "https://rumble.com/v6r0vz6-automate.html"

jobs:
  rumble-vpn:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup VPN and Run Puppeteer
        run: |
          # Disable immediate exit on error in the host shell
          set +e
          
          docker run --rm --privileged --cap-add=NET_ADMIN --security-opt seccomp=unconfined --security-opt apparmor=unconfined ubuntu:latest bash -c "
            export DEBIAN_FRONTEND=noninteractive
            
            # Install dependencies
            echo 'Installing dependencies...'
            apt update
            apt install -y curl wget openvpn ca-certificates iproute2 unzip gnupg nodejs npm fonts-liberation libatk-bridge2.0-0 libatk1.0-0 libatspi2.0-0 libcups2 libdbus-1-3 libgbm1 libgtk-3-0 libnspr4 libnss3 libpango-1.0-0 libx11-6 libxcb1 libxcomposite1 libxdamage1 libxext6 libxfixes3 libxrandr2 libxshmfence1 libxss1 libasound2 libpulse0 libxkbcommon0 xdg-utils
            
            # Set up OpenVPN with PIA
            echo 'Setting up OpenVPN connection to PIA...'
            mkdir -p /tmp/pia
            cd /tmp/pia
            wget -q https://www.privateinternetaccess.com/openvpn/openvpn.zip
            unzip -q openvpn.zip
            
            # Create credentials file
            echo '${{ secrets.PIA_USERNAME }}' > /tmp/pia/auth.txt
            echo '${{ secrets.PIA_PASSWORD }}' >> /tmp/pia/auth.txt
            chmod 600 /tmp/pia/auth.txt
            
            # Use US East server as it was proven reliable
            SERVER_FILE=/tmp/pia/us_east.ovpn
            
            # Modify the auth-user-pass line to point to our auth file
            sed -i 's/auth-user-pass/auth-user-pass \/tmp\/pia\/auth.txt/' \$SERVER_FILE
            
            # Start OpenVPN
            echo 'Starting OpenVPN connection...'
            openvpn --config \$SERVER_FILE --daemon --log /tmp/openvpn.log
            
            # Wait for connection
            echo 'Waiting for VPN interface to establish...'
            success=false
            for i in \$(seq 1 10); do
              echo \"Checking for VPN interface (attempt \$i)...\"
              if ip a | grep -q tun0; then
                success=true
                echo \"VPN interface detected!\"
                ip a show tun0
                echo \"VPN routing table:\"
                ip route
                break
              fi
              sleep 3
            done
            
            if [ \"\$success\" != true ]; then
              echo \"VPN Connection Failed\"
              cat /tmp/openvpn.log
              exit 1
            fi
            
            # Verify we have a different IP now
            echo \"Checking VPN IP:\"
            curl -s https://api.ipify.org || echo \"IP check timed out (expected through VPN)\"
            
            # Set up Puppeteer
            echo 'Setting up Puppeteer...'
            mkdir -p /app
            cd /app
            npm init -y
            npm install puppeteer puppeteer-core puppeteer-extra puppeteer-extra-plugin-stealth
            
            # Create a file system to write back to the host
            mkdir -p /app/screenshots
            
            # Create Puppeteer script
            cat > /app/rumble-visit.js << 'EOL'
            const puppeteer = require('puppeteer-extra');
            const StealthPlugin = require('puppeteer-extra-plugin-stealth');
            const fs = require('fs');
            const { execSync } = require('child_process');

            puppeteer.use(StealthPlugin());

            function sleep(ms) {
                return new Promise(resolve => setTimeout(resolve, ms));
            }

            async function safeScreenshot(page, path) {
                try {
                    await page.screenshot({ path });
                    console.log(\`Screenshot taken: \${path}\`);
                } catch (err) {
                    console.error(\`Failed to take screenshot \${path}: \${err.message}\`);
                }
            }

            async function reconnectVPN() {
                console.log(\"Reconnecting to a different VPN server...\");
                try {
                    // Disconnect and reconnect using OpenVPN
                    execSync(\"pkill -9 openvpn\", { stdio: 'inherit' });
                    await sleep(5000);
                    
                    // Find alternate server file
                    const servers = ['us_west.ovpn', 'us_california.ovpn', 'us_new_york.ovpn', 'us_atlanta.ovpn'];
                    let serverFile = '';
                    
                    for (const server of servers) {
                        if (fs.existsSync(\`/tmp/pia/\${server}\`)) {
                            serverFile = \`/tmp/pia/\${server}\`;
                            break;
                        }
                    }
                    
                    if (!serverFile) {
                        console.log(\"No alternate server file found, using default\");
                        serverFile = '/tmp/pia/us_east.ovpn';
                    }
                    
                    console.log(\`Connecting to server: \${serverFile}\`);
                    execSync(\`openvpn --config \${serverFile} --auth-user-pass /tmp/pia/auth.txt --daemon --log /tmp/openvpn.log\`, { stdio: 'inherit' });
                    
                    await sleep(10000);
                    
                    // Check if VPN is up
                    for (let i = 0; i < 10; i++) {
                        try {
                            const ifConfig = execSync(\"ip a | grep tun0\").toString();
                            if (ifConfig.includes('tun0')) {
                                console.log(\"VPN reconnected successfully\");
                                return true;
                            }
                        } catch (e) {
                            console.log(\"Waiting for VPN interface...\");
                        }
                        await sleep(1000);
                    }
                    
                    console.log(\"Failed to reconnect VPN\");
                    return false;
                } catch (error) {
                    console.error(\"Error during VPN reconnection:\", error.message);
                    return false;
                }
            }

            async function visitRumble(videoUrl) {
                let browser = await puppeteer.launch({
                    headless: \"new\",
                    ignoreHTTPSErrors: true,
                    executablePath: require('puppeteer').executablePath(),
                    args: ['--no-sandbox', '--disable-setuid-sandbox']
                });

                let page = await browser.newPage();
                await page.setUserAgent('Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 Chrome/133.0.0.0 Safari/537.36');
                await page.setCacheEnabled(false);

                console.log(\"Navigating to Rumble video...\");
                await page.goto(videoUrl, { waitUntil: 'networkidle2', timeout: 120000 });
                await sleep(3000);
                await safeScreenshot(page, \`./screenshots/rumble_landing_\${Date.now()}.png\`);

                const playButtonSelectors = [
                    '.bigPlayUIInner.ctp',
                    'button[aria-label=\"Play\"]',
                    '.vjs-big-play-button',
                    '.icon-play',
                    'div[class*=play]'
                ];

                let playButton = null;
                for (const selector of playButtonSelectors) {
                    playButton = await page.\$(selector);
                    if (playButton) {
                        console.log(\`Play button found using selector: \${selector}\`);
                        await playButton.click();
                        await sleep(3000);
                        await safeScreenshot(page, \`./screenshots/rumble_play_clicked_\${Date.now()}.png\`);
                        break;
                    }
                }

                if (!playButton) {
                    console.warn(\"Play button not found. Proceeding without clicking.\");
                }

                for (let t = 5; t <= 30; t += 5) {
                    await sleep(5000);
                    await safeScreenshot(page, \`./screenshots/rumble_watch_\${t}s_\${Date.now()}.png\`);
                    const isPlaying = await page.evaluate(() => {
                        const video = document.querySelector(\"video\");
                        return video && !video.paused && !video.ended && video.readyState > 2;
                    });

                    if (!isPlaying) {
                        console.log(\"Video is not playing. Attempting VPN reconnect...\");
                        await browser.close();
                        const reconnected = await reconnectVPN();
                        if (reconnected) {
                            return await visitRumble(videoUrl);
                        } else {
                            throw new Error(\"VPN reconnect failed. Aborting.\");
                        }
                    }
                }

                const finalHtml = await page.content();
                const htmlFile = \`./screenshots/final_rumble_page_\${Date.now()}.html\`;
                fs.writeFileSync(htmlFile, finalHtml);
                console.log(\`Final HTML page saved: \${htmlFile}\`);
                await browser.close();
            }

            async function run() {
                const videoUrl = process.argv[2] || \"https://rumble.com/v6r0vz6-automate.html\";
                await visitRumble(videoUrl);
            }

            run().catch(error => {
                console.error(\"Script failed:\", error.message);
            });
            EOL

            # Run Puppeteer script
            echo 'Running Puppeteer script...'
            VIDEO_URL=\"\$VIDEO_URL\"
            if [ -z \"\$VIDEO_URL\" ]; then
                VIDEO_URL=\"https://rumble.com/v6r0vz6-automate.html\"
            fi
            echo \"Visiting: \$VIDEO_URL\"
            node /app/rumble-visit.js \"\$VIDEO_URL\" | tee /app/puppeteer.log
            
            # Copy screenshots and logs to a location accessible from the host
            cp -r /app/screenshots /screenshots
            cp /app/puppeteer.log /puppeteer.log
            cp /tmp/openvpn.log /openvpn.log
          " -e "VIDEO_URL=${{ github.event.inputs.video_url }}"
          
          # Copy artifacts from Docker container
          mkdir -p screenshots
          docker cp $(docker ps -lq):/screenshots ./screenshots
          docker cp $(docker ps -lq):/puppeteer.log ./puppeteer.log
          docker cp $(docker ps -lq):/openvpn.log ./openvpn.log

      - name: Upload Debug Artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: rumble-debug-artifact-${{ runner.os }}
          path: |
            screenshots/
            puppeteer.log
            openvpn.log
          retention-days: 7
