name: Rumble Visit with VPN in Container

on:
  push:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:
    inputs:
      video_url:
        description: "Rumble Video URL"
        required: true
        default: "https://rumble.com/v6r0vz6-automate.html"

jobs:
  rumble-vpn:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Create Script Directory
        run: |
          mkdir -p screenshots
          mkdir -p logs

      - name: Run OpenVPN Connection and Network Diagnostics
        run: |
          docker run --rm --privileged --cap-add=NET_ADMIN --security-opt seccomp=unconfined --security-opt apparmor=unconfined ubuntu:latest bash -c "
            set -e
            export DEBIAN_FRONTEND=noninteractive
            
            echo 'Installing basic dependencies...'
            apt-get update
            apt-get install -y wget unzip openvpn ca-certificates iproute2 curl iputils-ping traceroute dnsutils
            
            # Check initial network
            echo 'Initial Network State:'
            echo 'IP address:'
            curl -s https://api.ipify.org || echo 'Failed to get initial IP'
            echo 'DNS resolution:'
            dig +short google.com
            echo 'Traceroute to Google DNS:'
            traceroute -n -m 5 8.8.8.8 || echo 'Initial traceroute failed'
            
            echo 'Setting up OpenVPN connection to PIA...'
            mkdir -p /tmp/pia
            cd /tmp/pia
            wget -q https://www.privateinternetaccess.com/openvpn/openvpn.zip
            unzip -q openvpn.zip
            
            echo 'Creating credentials file...'
            echo '${{ secrets.PIA_USERNAME }}' > /tmp/pia/auth.txt
            echo '${{ secrets.PIA_PASSWORD }}' >> /tmp/pia/auth.txt
            chmod 600 /tmp/pia/auth.txt
            
            echo 'Starting OpenVPN connection...'
            SERVER_FILE=/tmp/pia/us_east.ovpn
            sed -i 's/auth-user-pass/auth-user-pass \/tmp\/pia\/auth.txt/' \$SERVER_FILE
            # Enable more verbose logging
            sed -i 's/verb 1/verb 4/' \$SERVER_FILE
            openvpn --config \$SERVER_FILE --daemon --log /tmp/openvpn.log
            
            echo 'Waiting for VPN interface to establish...'
            for i in \$(seq 1 12); do
              echo \"Checking for VPN interface (attempt \$i)...\"
              if ip a | grep -q tun0; then
                echo \"VPN interface detected!\"
                ip a show tun0
                echo \"VPN routing table:\"
                ip route
                
                # Wait a bit for routes to establish
                sleep 5
                
                # Comprehensive network testing through VPN
                echo \"Testing DNS through VPN:\"
                dig +short google.com || echo \"DNS resolution failed through VPN\"
                
                echo \"Testing ping through VPN:\"
                ping -c 3 8.8.8.8 || echo \"Ping failed through VPN\"
                
                echo \"Testing traceroute through VPN:\"
                traceroute -n -m 10 8.8.8.8 || echo \"Traceroute failed through VPN\"
                
                echo \"Testing multiple IP services through VPN:\"
                echo \"ipify.org:\"
                curl -s https://api.ipify.org || echo \"ipify.org timed out\"
                
                echo \"ifconfig.me:\"
                curl -s https://ifconfig.me || echo \"ifconfig.me timed out\"
                
                echo \"icanhazip.com:\"
                curl -s https://icanhazip.com || echo \"icanhazip.com timed out\"
                
                echo \"ip.me:\"
                curl -s https://ip.me || echo \"ip.me timed out\"
                
                echo \"VPN logs:\"
                cat /tmp/openvpn.log > /dev/stdout
                cp /tmp/openvpn.log /tmp/logs/openvpn.log
                
                echo \"Network diagnostics complete\"
                # Create logs directory and save results
                mkdir -p /tmp/logs
                ip a > /tmp/logs/interfaces.log
                ip route > /tmp/logs/routes.log
                break
              fi
              
              if [ \$i -eq 12 ]; then
                echo \"VPN Connection Failed\"
                cat /tmp/openvpn.log > /dev/stdout
                
                # Create logs directory and save failure logs
                mkdir -p /tmp/logs
                cat /tmp/openvpn.log > /tmp/logs/openvpn.log
                exit 1
              fi
              
              # Show more logs for debugging
              if [ \$((i % 2)) -eq 0 ]; then
                echo \"Current OpenVPN log:\"
                cat /tmp/openvpn.log | tail -30
              fi
              
              sleep 5
            done
            
            # Make logs accessible to the host user
            chmod -R 777 /tmp/logs
          "
          
          # Copy logs from Docker
          docker cp $(docker ps -lq):/tmp/logs ./logs
          chmod -R 755 ./logs

      - name: Upload Diagnostic Information
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: vpn-diagnostics
          path: |
            logs/
          retention-days: 7
